---
version: '2.0'
services:
  supabase:
    image: supabase/postgres
    expose:
      - port: 5432
        as: 5432
        to:
          - global: true
    command:
	- postgres -c config_file=/etc/postgresql/postgresql.conf
    env:
      - POSTGRES_PASSWORD=postgres
profiles:
  compute:
    supabase:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
          - name: supabase-db
            size: 4Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://docs.akash.network/providers/akash-audited-attributes
      pricing:
        supabase:
          denom: uakt
          amount: 10000
deployment:
  supabase:
    akash:
      profile: supabase
      count: 1
