---
version: "2.0"

services:
  wildrig-multi:
    image: cryptoandcoffee/akash-gpu-miner-wildrig-multi-c11:1
    expose:
      - port: 21550
        as: 80
        to:
          - global: true
    env:
      - ALGO=kawpow
      - WALLET_ADDRESS=""
      - POOL="stratum+ssl://kawpow.mine.zergpool.com:13638"
      - PASSWORD="c=ETC,m=solo" #Example mines kawpow algorithm and payout out in Ethereum Classic
      - OPTIONS="--api-port 21550"
#The default command. Adjust OPTIONS as needed.
#/root/wildrig-multi -a $ALGO -o $POOL -u $WALLET_ADDRESS -p $PASSWORD $OPTIONS
profiles:
  compute:
    wildrig-multi:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 768Mi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                #- model: 3090
        storage:
          - size: 128Mi
  placement:
    akash:
      pricing:
        wildrig-multi:
          denom: uakt
          amount: 1000000 #Keep high to show all bids
deployment:
  wildrig-multi:
    akash:
      profile: wildrig-multi
      count: 1