
---
version: "2.0"
services:
  service-1:
    image: ollama/ollama
    expose:
      - port: 11434
        as: 11434
        to:
          - global: true
    command:
      - /bin/sh
      - -c
      - |
        ollama serve & 
        while ! ollama pull llama3.1:8b; do
          echo "Waiting for ollama pull to succeed..."
          sleep 6
        done
        ollama list
        pkill ollama
        ollama serve

profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 32Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 10000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
