version: "2.0"
services:
  gpustack-worker:
    image: gpustack/gpustack:main
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 10151
        as: 10151
        to:
          - global: true
    env:
      - GPUSTACK_WORKER_PORT=80
      - GPUSTACK_TOKEN=6f7784c27c2bcbd014dca8b7bbfa45db
      - GPUSTACK_SERVER_URL=http://vaajbpjfqp92feilhq22eglcgg.ingress.a6000.mon.obl.akash.pub
profiles:
  compute:
    gpustack-worker:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 128Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    akash:
      attributes:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://akash.network/docs/providers/audited-attributes
      pricing:
        gpustack-worker:
          denom: uakt
          amount: 10000

deployment:
  gpustack-worker:
    akash:
      profile: gpustack-worker
      count: 1

