---
version: "2.0"
services:
  ollama:
    image: ollama/ollama
    expose:
      - port: 11434
        as: 80
        to:
          - global: false
          - service: open-webui
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    expose:
      - port: 8080
        as: 8080
        to:
          - global: true
    env:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
profiles:
  compute:
    ollama:
      resources:
        cpu:
          units: 8
        #Higher is better for AI! 
        memory:
          size: 28Gi
        #7B requires about 4.5GB of free RAM
        #13B requires about 12GB free
        #30B requires about 20GB free // 24 not enough
        storage:
          size: 100Gi
        #Bigger models may require more storage.
        #Increase as required.
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
    open-webui:
      resources:
        cpu:
          units: 1
        memory:
          size: 4Gi
        storage:
          - size: 16Gi
  placement:
    akash:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://docs.akash.network/providers/akash-audited-attributes
      pricing:
        ollama:
          denom: uakt
          amount: 10000
        open-webui:
          denom: uakt
          amount: 10000
deployment:
  ollama:
    akash:
      profile: ollama
      count: 1
  open-webui:
    akash:
      profile: open-webui
      count: 1
