---
version: "2.0"

services:
  xmrig-c11:
    image: cryptoandcoffee/akash-gpu-miner-xmrig-c11:9
    expose:
      - port: 8080
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - ALGO="rx/0"
      #Set the algorithm you want xmrig to use.
      - POOL="gulf.moneroocean.stream:20128"
      #The mining pool you want to connect to.
      - WALLET="4AbG74FRUHYXBLkvqM1f7QH3UXGkhLetKdxS7U7BHkyfMF4nfx99GvN1REwYQHAeVLLy4Qa5gXXkfS4pSHHUWwdVFifDo5K"
      #Your Monero Wallet Address for the default pool, otherwise any other wallet address for another pool/coin.
      - WORKER="akash"
      #All worker names have the provider domain as suffix, example akash-provider.akash.world
      - PASS="x"
      #Most pools do not require a password.  Only change this if you need to set a password.
      - TLS=true
      #Protect your shares by choosing pools that support encryption!
      - TLS_FINGERPRINT=
      #Use a TLS_FINGERPRINT if required.  Can be left blank.
      - CUSTOM_OPTIONS=
      #Customize the command line options of xmrig.  Full list of command available here:
      #https://xmrig.com/docs/miner/command-line-options
profiles:
  compute:
    xmrig-c11:
      resources:
        cpu:
          units: 0.5
          #Min 0.01 / Max 256 cpu.units
        memory:
          size: 3Gi
          #Min 3Gi with GPU!
        storage:
          size: 128Mi
          #Min 128Mi with GPU / Max 32Ti
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    akash:
      #######################################################
      #Keep this section to deploy on trusted providers
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      #######################################################
      #Remove this section to deploy on untrusted providers
      #Miners: You can receive more bids from more providers by removing this section
      #Beware* You may have deployment, security, or other issues on untrusted providers
      #https://docs.akash.network/providers/akash-audited-attributes
      pricing:
        xmrig-c11:
          denom: uakt
          amount: 100000 #Keep high to show all bids
deployment:
  xmrig-c11:
    akash:
      profile: xmrig-c11
      count: 1

##Total deployment size cannot exceed 512vCPU / 512Gi / 32Ti
##You can reduce vCPU and increase count:1 to see more bids
##Example: cpu.units:2 and akash.count:10 will show more bids than 10 cpu.units and akash.count 2.
