---
version: "2.0"

services:
  stable-diffusion-ui:
    image: cryptoandcoffee/akash-stable-diffusion-ui:3
    expose:
      - port: 9000
        as: 80
        to:
          - global: true

profiles:
  compute:
    stable-diffusion-ui:
      resources:
        cpu:
          units: 24
        memory:
          size: 16Gi
        storage:
          size: 64Gi

  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        stable-diffusion-ui:
          denom: uakt
          amount: 100000

deployment:
  stable-diffusion-ui:
    akash:
      profile: stable-diffusion-ui
      count: 1
